//! Validation helpers that combine Locus probe verdicts.

mod mapped_scratch_thp_gate;
mod pinned_scratch_gate;
mod pinned_scratch_near_gpu_gate;
mod remote_free_service_collection_summary;
mod remote_free_service_sample_compare;
mod remote_free_service_timing_stability;
mod thp_benchmark_evidence_report;
mod thp_benchmark_evidence_run_summary;
mod thp_fault_sample_comparison;
mod thp_fault_sample_gate;
mod thp_fault_sample_report;

pub use mapped_scratch_thp_gate::{
    evaluate_mapped_scratch_thp_validation_output, parse_mapped_scratch_thp_validation_gate_line,
    parse_mapped_scratch_thp_validation_gate_output, MappedScratchThpValidationGate,
    MappedScratchThpValidationGateLineParseError, MappedScratchThpValidationGateOutputParseError,
    MappedScratchThpValidationGateParseError, MappedScratchThpValidationGateReason,
    MappedScratchThpValidationGateStatus, MappedScratchThpValidationGateVerdict,
};
pub use pinned_scratch_gate::{
    evaluate_pinned_scratch_validation_output, parse_pinned_scratch_validation_gate_line,
    parse_pinned_scratch_validation_gate_output, PinnedScratchValidationGate,
    PinnedScratchValidationGateLineParseError, PinnedScratchValidationGateOutputParseError,
    PinnedScratchValidationGateParseError, PinnedScratchValidationGateReason,
    PinnedScratchValidationGateStatus, PinnedScratchValidationGateVerdict,
};
pub use pinned_scratch_near_gpu_gate::{
    evaluate_pinned_scratch_near_gpu_validation_output,
    parse_pinned_scratch_near_gpu_validation_gate_line, PinnedScratchNearGpuValidationGate,
    PinnedScratchNearGpuValidationGateLineParseError, PinnedScratchNearGpuValidationGateParseError,
    PinnedScratchNearGpuValidationGateReason, PinnedScratchNearGpuValidationGateStatus,
    PinnedScratchNearGpuValidationGateVerdict,
};
pub use remote_free_service_collection_summary::{
    build_remote_free_service_telemetry_collection_summary_directory_rollup,
    check_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_json_log,
    collect_remote_free_service_telemetry_collection_summary_paths,
    format_remote_free_service_telemetry_collection_summary_rollup_check_json_line,
    format_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_json_line,
    format_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_json_line,
    format_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_rollup_json_line,
    parse_remote_free_service_telemetry_collection_summary,
    parse_remote_free_service_telemetry_collection_summary_rollup_check_json_line,
    parse_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_json_line,
    parse_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_json_log,
    parse_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_json_line,
    parse_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_rollup_json_line,
    parse_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_rollup_json_log,
    resolve_remote_free_service_telemetry_collection_summary_manifest_path,
    resolve_remote_free_service_telemetry_collection_summary_validation_summary_path,
    summarize_remote_free_service_telemetry_collection_summary_rollup_check_json_log,
    summarize_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_json_log,
    validate_remote_free_service_telemetry_collection_summary_rollup_artifact,
    verify_remote_free_service_telemetry_collection_summary_artifacts,
    verify_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_json_log,
    verify_remote_free_service_telemetry_collection_summary_rollup_check_log_summary_verification_rollup_json_log,
    write_remote_free_service_telemetry_collection_summary_rollup_artifact,
    RemoteFreeServiceTelemetryCollectionSummary,
    RemoteFreeServiceTelemetryCollectionSummaryArtifact,
    RemoteFreeServiceTelemetryCollectionSummaryArtifactReport,
    RemoteFreeServiceTelemetryCollectionSummaryBundleValidation,
    RemoteFreeServiceTelemetryCollectionSummaryDirectoryRollupError,
    RemoteFreeServiceTelemetryCollectionSummaryError,
    RemoteFreeServiceTelemetryCollectionSummaryHost,
    RemoteFreeServiceTelemetryCollectionSummaryRollup,
    RemoteFreeServiceTelemetryCollectionSummaryRollupBundle,
    RemoteFreeServiceTelemetryCollectionSummaryRollupBundleStatus,
    RemoteFreeServiceTelemetryCollectionSummaryRollupCheck,
    RemoteFreeServiceTelemetryCollectionSummaryRollupCheckLogSummary,
    RemoteFreeServiceTelemetryCollectionSummaryRollupCheckLogSummaryDrift,
    RemoteFreeServiceTelemetryCollectionSummaryRollupCheckLogSummaryVerification,
    RemoteFreeServiceTelemetryCollectionSummaryRollupCheckLogSummaryVerificationRollup,
    RemoteFreeServiceTelemetryCollectionSummaryRollupError,
    RemoteFreeServiceTelemetryCollectionSummaryRollupHost,
    RemoteFreeServiceTelemetryCollectionSummaryScanError,
    RemoteFreeServiceTelemetryCollectionSummarySource,
    REMOTE_FREE_SERVICE_TELEMETRY_COLLECTION_SUMMARY_ROLLUP_CHECK_LOG_SCHEMA,
    REMOTE_FREE_SERVICE_TELEMETRY_COLLECTION_SUMMARY_ROLLUP_CHECK_LOG_SUMMARY_VERIFICATION_ROLLUP_SCHEMA,
    REMOTE_FREE_SERVICE_TELEMETRY_COLLECTION_SUMMARY_ROLLUP_CHECK_LOG_SUMMARY_VERIFICATION_SCHEMA,
    REMOTE_FREE_SERVICE_TELEMETRY_COLLECTION_SUMMARY_ROLLUP_CHECK_SCHEMA,
    REMOTE_FREE_SERVICE_TELEMETRY_COLLECTION_SUMMARY_ROLLUP_SCHEMA,
    REMOTE_FREE_SERVICE_TELEMETRY_COLLECTION_SUMMARY_SCHEMA,
};
pub use remote_free_service_sample_compare::{
    compare_remote_free_service_telemetry_sample_outputs,
    compare_remote_free_service_telemetry_sample_outputs_with_timings,
    parse_remote_free_service_telemetry_sample_rows, parse_remote_free_service_telemetry_timings,
    RemoteFreeServiceTelemetrySampleCompareReport, RemoteFreeServiceTelemetrySampleCompareStatus,
    RemoteFreeServiceTelemetrySampleDrift, RemoteFreeServiceTelemetrySampleKey,
    RemoteFreeServiceTelemetrySampleParseError, RemoteFreeServiceTelemetrySampleRow,
    RemoteFreeServiceTelemetrySampleTimingCompareError,
    RemoteFreeServiceTelemetrySampleTimingCompareReport,
    RemoteFreeServiceTelemetrySampleTimingCompareStatus, RemoteFreeServiceTelemetryTimingDelta,
    RemoteFreeServiceTelemetryTimingInterval, RemoteFreeServiceTelemetryTimingParseError,
};
pub use remote_free_service_timing_stability::{
    format_remote_free_service_telemetry_timing_stability_manifest,
    parse_remote_free_service_telemetry_timing_stability_manifest,
    remote_free_service_telemetry_repeated_capture_labels,
    summarize_remote_free_service_telemetry_timing_stability,
    RemoteFreeServiceTelemetryTimingStabilityDiscard,
    RemoteFreeServiceTelemetryTimingStabilityError,
    RemoteFreeServiceTelemetryTimingStabilityManifest,
    RemoteFreeServiceTelemetryTimingStabilityManifestEntry,
    RemoteFreeServiceTelemetryTimingStabilityManifestFormatError,
    RemoteFreeServiceTelemetryTimingStabilityManifestParseError,
    RemoteFreeServiceTelemetryTimingStabilityManifestRole,
    RemoteFreeServiceTelemetryTimingStabilityRange,
    RemoteFreeServiceTelemetryTimingStabilityReport, RemoteFreeServiceTelemetryTimingStabilityRun,
    RemoteFreeServiceTelemetryTimingStabilityStatus,
};
pub use thp_benchmark_evidence_report::{
    parse_mapped_scratch_thp_benchmark_evidence_report_output,
    MappedScratchThpBenchmarkEvidenceReason, MappedScratchThpBenchmarkEvidenceReport,
    MappedScratchThpBenchmarkEvidenceReportParseError, MappedScratchThpBenchmarkEvidenceStatus,
    MappedScratchThpBenchmarkTimings, MappedScratchThpBenchmarkTimingsParseError,
    MappedScratchThpTimingInterval,
};
pub use thp_benchmark_evidence_run_summary::{
    summarize_mapped_scratch_thp_benchmark_evidence_report_lines,
    MappedScratchThpBenchmarkEvidenceRunCohort,
    MappedScratchThpBenchmarkEvidenceRunPolicyCandidateReason,
    MappedScratchThpBenchmarkEvidenceRunSummary,
    MappedScratchThpBenchmarkEvidenceRunSummaryParseError,
};
pub use thp_fault_sample_comparison::{
    parse_mapped_scratch_thp_fault_sample_comparison_line,
    parse_mapped_scratch_thp_fault_sample_comparison_output,
    MappedScratchThpFaultSampleComparisonLineParseError,
    MappedScratchThpFaultSampleComparisonOutput,
    MappedScratchThpFaultSampleComparisonOutputParseError,
    MappedScratchThpFaultSampleComparisonReason, MappedScratchThpFaultSampleComparisonStatus,
};
pub use thp_fault_sample_gate::{
    evaluate_mapped_scratch_thp_fault_sample_validation_output,
    parse_mapped_scratch_thp_fault_sample_validation_gate_line,
    parse_mapped_scratch_thp_fault_sample_validation_gate_output,
    MappedScratchThpFaultSampleValidationGate,
    MappedScratchThpFaultSampleValidationGateLineParseError,
    MappedScratchThpFaultSampleValidationGateOutputParseError,
    MappedScratchThpFaultSampleValidationGateParseError,
    MappedScratchThpFaultSampleValidationGateReason,
    MappedScratchThpFaultSampleValidationGateStatus,
    MappedScratchThpFaultSampleValidationGateVerdict,
};
pub use thp_fault_sample_report::{
    parse_mapped_scratch_thp_fault_sample_report_output, MappedScratchThpFaultSampleReport,
    MappedScratchThpFaultSampleReportParseError,
};

#[cfg(target_os = "linux")]
pub mod linux;
